"""Small database abstraction supporting SQLite locally and PostgreSQL on Render."""
import sqlite3
from pathlib import Path
from flask import current_app, g


def _sqlite_connection():
    path = Path(current_app.config["SQLITE_PATH"])
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn


def get_db():
    if "db" not in g:
        # psycopg is deliberately lazy: local development needs no database service.
        url = current_app.config.get("DATABASE_URL")
        if url:
            import psycopg
            g.db = psycopg.connect(url, row_factory=psycopg.rows.dict_row)
        else:
            g.db = _sqlite_connection()
    return g.db


def close_db(_error=None):
    conn = g.pop("db", None)
    if conn is not None:
        conn.close()


def execute(sql, params=()):
    conn = get_db()
    # SQL in this project uses qmark placeholders; convert for psycopg.
    if current_app.config.get("DATABASE_URL"):
        sql = sql.replace("?", "%s")
    cur = conn.execute(sql, params) if hasattr(conn, "execute") else conn.cursor().execute(sql, params)
    conn.commit()
    return cur


def insert_id(sql, params=()):
    """Insert a record and return its primary key on SQLite and PostgreSQL."""
    conn = get_db()
    sql = sql.rstrip() + " RETURNING id"
    if current_app.config.get("DATABASE_URL"):
        sql = sql.replace("?", "%s")
    cur = conn.execute(sql, params) if hasattr(conn, "execute") else conn.cursor().execute(sql, params)
    row = cur.fetchone()
    conn.commit()
    return row["id"] if isinstance(row, dict) or hasattr(row, "keys") else row[0]


def init_db():
    schema_path = Path(current_app.root_path).parent / "database" / "schema.sql"
    schema = schema_path.read_text(encoding="utf-8")
    conn = get_db()
    if current_app.config.get("DATABASE_URL"):
        # PostgreSQL accepts statements one by one; schema is intentionally portable.
        schema = schema.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        for statement in schema.split(";"):
            if statement.strip():
                conn.execute(statement)
        conn.commit()
    else:
        conn.executescript(schema)
        conn.commit()
